---

- name: Install node-gyp globally
  include_role: 
    name: root
    tasks_from: node-gyp.yml
  become: true
  become_user: root

- include: iquippo.yml
  tags: iquippo
  become: true
  become_user: imran_54650

