---

- name: Deploy Application
  hosts: "{{ host }}"
  roles: 
    - www
  become: true
  become_user: jenkinsUAT
  become_method:  su
  tags: [site-deployment,lamp-test]


- name: Building Mysql 
  hosts: "{{ host }}"
  roles: 
    - db
#  become: true
#  become_user: www-data
  tags: [db]