#---
#
#- name: Deploy Application
#  hosts: "{{ host }}"
#  roles: 
#    - www
#  become: true
#  become_user: www-data
#  tags: [site-deployment,lamp-test]
#
#
#- name: Deploy Application
#  hosts: "{{ host }}"
#  roles: 
#    - db
#  become: true
#  become_user: www-data
#  tags: [db]

---

- name: Deploy Application
  hosts: "{{ host }}"
  roles: 
    - www
  become: true
  # THis will be the user which we will use for deployment..constant 
  become_user: root
  tags: [site-deployment,lamp-test]
  
  
